### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by 5E7EN** [tcollinsworth/axios-cached-dns-resolve#23]
My typescript project fails to compile, spitting out the following error:

```
C:\...\node_modules\axios-cached-dns-resolve\index.js:1
export {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\...\build\lib\helpers\network-manager.js:65:34)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

From what I've seen in the past, this was a bug and has been resolved in past versions, however I am using v3.0.6 (latest as of writing), and still encounter this error.

Attempting to add `"type": "module"` to my package.json let to unexpected behavior, and isn't a solution for me either.

**Comment by tcollinsworth** [comment]
load the package esm or esm-wallaby before loading this module.

**Comment by tcollinsworth** [comment]
node -r esm ...
or
node -r esm-wallaby ...
